---
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - docs/**
github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - pyproject.toml
          - uv.lock
tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**
examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**
confluent:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/confluent/**
          - tests/integration/test_confluent.py
          - examples/confluent/**
kafka:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/kafka/**
          - tests/integration/test_kafka.py
          - examples/kafka/**
mqtt:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/mqtt/**
          - tests/integration/test_mqtt.py
          - examples/mqtt/**
nats:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/nats/**
          - tests/integration/test_nats.py
          - examples/nats/**
postgres:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/postgres/**
          - tests/integration/test_postgres.py
          - examples/postgres/**
pubsub:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/pubsub/**
          - tests/integration/test_pubsub.py
          - examples/pubsub/**
rabbit:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/rabbit/**
          - tests/integration/test_rabbit.py
          - examples/rabbit/**
redis:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/redis/**
          - tests/integration/test_redis.py
          - examples/redis/**
sqs:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/sqs/**
          - tests/integration/test_sqs.py
          - examples/sqs/**
zmq:
  - changed-files:
      - any-glob-to-any-file:
          - src/litestar_events/contrib/zmq/**
          - tests/integration/test_zmq.py
          - examples/zmq/**
